### ISSUE TITLE
Support for SendGrid at Azure?

### ISSUE THREAD

**Issue by sovaska** [0xdeafcafe/sendgrid-dotnet#2]
As far as I understand, there is no "SendGrid Api key" if you use SendGrid from Azure. There are only username, password and smtp server information. Any plans to add support for Azure SendGrid for this library?

**Comment by andrewbasarab** [comment]
@sovaska You can get api keys on app.sendgrid.com.
Go to new Azure portal -> SendGrid -> press "Manage" button -> azure will redirect you to app.sendgrid.com where you can get api keys.

**Comment by 0xdeafcafe** [comment]
Yeah, just follow @abasarab's instructions. Sorry for not replying @sovaska , I think when I saw this notification I thought it was on the official repo.
