### ISSUE TITLE
Using substitutions in Trasactional Templates

### ISSUE THREAD

**Issue by gldraphael** [0xdeafcafe/sendgrid-dotnet#3]
Are transactional email templates supported?

I've got something like this right now:

```C#
var key = new ApiKeyConnection("SG.xxxxxxxxxx--xx_xxxxxxx.xxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxx");
var client = new SendGridClient(key);
client.MailClient.SendAsync(new Email
{
    Personalizations = new List<Personalization>
    {
        new Personalization
        {
            To = new List<EmailDetail>
            {
                new EmailDetail
                {
                    Email = "email@gmail.com",
                    Name = "Galdin Raphael"
                }
            }
        }
    },
    From = new EmailDetail
    {
        Email = "email@domain.com",
        Name = "Name"
    },
    Subject = "Subject",
    TemplateId = "xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxxx"
}).Wait();
```

Can't get substitutions to work though

**Comment by 0xdeafcafe** [comment]
I've just pushed a [commit](1b43788a732866f02ffed31af924c3b2113f0218) that added substitutions and sections to the models. Check the `sections` field in the Email model, and the `substitutions` field in the Personalization model. It's on nuget as `2.0.0-preview2`. Let me know if that works.

**Comment by gldraphael** [comment]
Wow that was quick. I'll update you in a few minutes :)

**Comment by gldraphael** [comment]
Nope doesn't seem to work.
Why is the does the `Email` model have a `sections` field. Shouldn't it be `substitutions` too?
I'm looking at this: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

**Comment by gldraphael** [comment]
My bad, it worked. I checked the wrong email.
Thanks a lot!

**Comment by 0xdeafcafe** [comment]
Awesome. And it's `substitutions` in the `Personalization`. No idea why it's `sections` in the `Email` model. 💁🏼
